server:
  port: 8082
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/deloitteRatingService
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: dishes-service
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/