spring:
  application:
    name: get-info-service
    
server:
  port: 8083
  
  
  
#--circuit breaker
resilience4j:
  circuitbreaker:
    instances:
      getDishInfobyDishIdBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 1s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED